apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: sampleingress
  name: sampleingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: sampleservice
          servicePort: 80
        path: /
